
server:
  port: 8769
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iuoooo/config.git
          search-paths: conf
        default-label: master
  #        native:
#          search-locations: classpath:/shared
    #  profiles:
  #    active: native
  application:
    name: config-sever